//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionLib.IntegrationTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class OrionTestSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OrionTestSettings defaultInstance = ((OrionTestSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OrionTestSettings())));
        
        public static OrionTestSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6001/")]
        public string SubscriptionAddress {
            get {
                return ((string)(this["SubscriptionAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://orionhost:1026")]
        public string OrionAddress {
            get {
                return ((string)(this["OrionAddress"]));
            }
        }
    }
}
